### ISSUE TITLE
Readme conflict

### ISSUE THREAD

**Issue by ShiranAvidov** [serilog-contrib/Serilog.Sinks.Logz.Io#25]
Hi, 
in the readme first paragraph you recommend to use Serilog.Sinks.Http.LogzIo, but in the Serilog.Sinks.Http.LogzIo section you say it has been deprecated and you recommend to use Serilog.Sinks.Logz.Io latest version.

**Comment by mantasaudickas** [comment]
Sorry about that. Removed misleading paragraph.
