### ISSUE TITLE
Possible to truncate string property message length?

### ISSUE THREAD

**Issue by arisliang** [serilog-contrib/Serilog.Sinks.Logz.Io#27]
In case some string property is too long, is it possible to set a maximum length by property name?

**Comment by mantasaudickas** [comment]
Thanks for bringing this up, but I guess this is not very trivial as I guess not only property can be too long, but a final payload containing multiple long properties can also become too long.

**Comment by arisliang** [comment]
Yes, indeed. But as a start, if user know certain property could be pretty long (such as stacktrace), they can set maximum to truncate that property (or for any property), it would help to bring the whole payload down.
